### ISSUE TITLE
Printing documentation from web page

### ISSUE THREAD

**Issue by yoonghm** [duckdb/duckdb-web#5510]
I try to print https://duckdb.org/docs/stable/core_extensions/ducklake.html but it included the left navigation and the right sidebar.

I have also tried to highlight the main contains and print but the long line of code are truncated.

I used the following css to remove the left navigation and the right sidebar:

```css
@media print {
  header, footer, .sidenavigation, #sidebar {
    display: none !important;
  }

  .wrap.ducklake {
    width: 100%; !important;
    max-width: 100% !important;
    margin: 0 auto !important;
    padding: 0 20px !important;
  }

  body.documentation main .wrap {
    width: 100% !important; 
  }
  
  #main_content_wrap {
    margin-top: 0px !important;
    width: 100% !important;
    max-width: 100% !important;
    padding: 0px !important;
  }
}
```

Could something be done so that the css could be applied to all web pages from https://duckdb.org/docs/?

I think it is in https://github.com/duckdb/duckdb-web/blob/main/_sass/base/_base.scss
